  CREATE TABLE "FILE"
   (	ID NUMBER NOT NULL,
   CONSTRAINT FILE_PK PRIMARY KEY (ID),
	NAME VARCHAR2(10) NOT NULL,
	"FORMAT" VARCHAR2(20),
	"SIZE" NUMBER NOT NULL,
	STORAGE_ID NUMBER,
	 CONSTRAINT FILE_FK1 FOREIGN KEY (STORAGE_ID)
	  REFERENCES STORAGE (ID)
	  );